### ISSUE TITLE
[Feature Request] make latches of connectors better available

### ISSUE THREAD

**Issue by generationmake** [pika-spark/pika-spark-enclosure#5]
The connectors for CAN and RS485 (and maybe 10BASE-T1S) have latches and these are now partly blocked by the top part of the enclosure.
Decrease the size of the top-enclosure in the area of these connectors.

**Comment by aentinger** [comment]
I just checked and I agree 👍 

![IMG_20230702_181015_256](https://github.com/pika-spark/pika-spark-enclosure/assets/3931733/d704f043-66e6-4424-9187-93ced099c3e4)
![IMG_20230702_181007_185](https://github.com/pika-spark/pika-spark-enclosure/assets/3931733/f5a71225-aea4-4f7a-90ef-f229adc3b133)
