### ISSUE TITLE
[Feature Request] USB-C - openings left and right of connector should be of the same length (symmetric placement of USB-C connector)

### ISSUE THREAD

**Issue by aentinger** [pika-spark/pika-spark-enclosure#8]
![usb-c-symmetrical](https://github.com/pika-spark/pika-spark-enclosure/assets/3931733/318952c9-469d-4c6b-9ce7-c858784196a6)

**Comment by generationmake** [comment]
Hi @aentinger 
according to the 3d data this opening should be nearly symmetric.
maybe the Pika Spark isn't place correctly above its mounting posts? Could you please add some screws?

**Comment by aentinger** [comment]
Screws are in and pika spark is placed correctly above its mounting posts.

![IMG_20230727_190143_448](https://github.com/pika-spark/pika-spark-enclosure/assets/3931733/9aa95870-5366-474d-8b37-c05f063ad880)
