### ISSUE TITLE
[Feature Request] Increase wall thickness at isolation transformer to close gap when mounting TOP enclosure

### ISSUE THREAD

**Issue by aentinger** [pika-spark/pika-spark-enclosure#9]
![thicker-wall-close-gap](https://github.com/pika-spark/pika-spark-enclosure/assets/3931733/2a9860f3-73bc-4730-94ac-41c49a3f9a96)

![thicker-wall-close-gap-2](https://github.com/pika-spark/pika-spark-enclosure/assets/3931733/d70f1647-3de0-4781-97ed-9e9f7eacbb04)

**Comment by generationmake** [comment]
won't be fixed because there will be no cut out for the transformer in the future!
